### ISSUE TITLE
Error when including both stellar-hd-wallet and stellar-sdk in my project

### ISSUE THREAD

**Issue by corymsmith** [chatch/stellar-hd-wallet#10]
When I include both `stellar-hd-wallet` and `stellar-sdk` in my project I get errors when requiring them both as `stellar-base` is included twice, not sure if `stellar-base` should instead be a `peerDependency` or how to solve this...

Any suggestions? 

```
Error: XDR Error:Value is already defined
    at TypeBuilder.define (/code/blockchain-client/node_modules/js-xdr/lib/config.js:341:17)
    at TypeBuilder.typedef (/code/blockchain-client/node_modules/js-xdr/lib/config.js:247:14)
    at /code/blockchain-client/node_modules/stellar-hd-wallet/node_modules/stellar-base/lib/generated/stellar-xdr_generated.js:1:259
    at Object.config (/code/blockchain-client/node_modules/js-xdr/lib/config.js:38:5)
    at Object.<anonymous> (//code/blockchain-client/node_modules/stellar-hd-wallet/node_modules/stellar-base/lib/generated/stellar-xdr_generated.js:1:234)
```

These are the related deps in my package.json: 
```
"stellar-hd-wallet": "0.0.6",
"stellar-sdk": "^0.9.2"
```

**Comment by corymsmith** [comment]
Related to https://github.com/stellar/js-stellar-sdk/issues/191

**Comment by chatch** [comment]
i'm not sure what's going on here.  the "TS errors", is that typescript executing the code? or tsc compiling?

**Comment by corymsmith** [comment]
This just happens when requiring them. I realized it's not actually TypeScript errors.

**Comment by johansten** [comment]
I'm getting the same with webpack/babel. The solution was to upgrade `stellar-hd-wallet` to use the same version of `stellar-base` as `stellar-sdk` is using.

**Comment by chatch** [comment]
ok great.  thanks @johansten.  i'll do a release with this fix now.

**Comment by chatch** [comment]
released 0.0.7 to npm which includes this fix.

**Comment by bartekn** [comment]
Fix ready in https://github.com/stellar/js-xdr/pull/21.

**Comment by bartekn** [comment]
This is fixed in:
* `js-xdr@1.0.4`
* `stellar-base@0.8.2`
* `stellar-sdk@0.10.2`

**Comment by chatch** [comment]
awesome. thanks @bartekn, i will deploy a new version with the new stellar-base version,
