### ISSUE TITLE
update stellar-base dependency

### ISSUE THREAD

**Issue by Ebioro** [chatch/stellar-hd-wallet#13]
Tried to use the wallet for an angular 6 project and could not build it because the angular cli started complaining about the crypto library.  I then found out that wallet is currently using the stellar-base 0.11. The guys from stellar have removed the crypto library in version 0.13 of the stellar-base sdk which should have fixed the issue. More details can be found [here](https://github.com/stellar/js-stellar-base/issues/128)

**Comment by chatch** [comment]
thanks @Ebioro   i've updated and published new release 0.10.0

**Comment by Ebioro** [comment]
you are welcome! I had an open question on stellar stack exchange about this (under yulemata username) I will add there that you guys have updated it and publish a new release!
