### ISSUE TITLE
how to get secret key by 12 recovery phrase in stellar lobstr vault account ? easy word explanation

### ISSUE THREAD

**Issue by masoud-abbasi** [chatch/stellar-hd-wallet#15]
hi
I create a stellar account in lobstr vault application and I got public key and 12 recovery phrase .
now I want to transfer the crypto from lobstr wallet , but it is needed the secret key which is not received from lobstr vault.
I checked the several third party application , but not useful < 
would you please explain me in easy word how to get secret key 
thanks

**Comment by whackur** [comment]
Example Code bellow.

```
const StellarHDWallet = require('stellar-hd-wallet');

const decodeMnemonic = async (mnemonic) => {
  const wallet = await StellarHDWallet.fromMnemonic(mnemonic);
  const publicKey = wallet.getPublicKey(0).toString();
  const secretKey = wallet.getSecret(0).toString();
}
```

**Comment by masoud-abbasi** [comment]
var stellarHdWallet = require("stellar-hd-wallet");

const mnemonic = '  12 mnemonic phrase  ';
const wallet = stellarHdWallet.fromMnemonic(mnemonic)
console.log('secret key: ' + wallet.getSecret(0))
console.log('key pair: ' + wallet.getKeypair(0))
console.log('public key: ' + wallet.getPublicKey(0))
