### ISSUE TITLE
How do you create/add additional keypairs?

### ISSUE THREAD

**Issue by chrisabrams** [chatch/stellar-hd-wallet#2]
Since you can select the index of the keypair, how would you create/add new ones?

**Comment by chatch** [comment]
hi @chrisabrams, all keys are generated deterministically from the seed. so if you need a new one just pick a new index down the chain and fetch the keypair for that index.

**Comment by chatch** [comment]
specifically, use getKeypair:

wallet.getKeypair(idx)
