### ISSUE TITLE
Steller account does not address hex 

### ISSUE THREAD

**Issue by nagarajmanjunath** [chatch/stellar-hd-wallet#6]
I  was checking  "stellar-hd-wallet" ,It generate only secret Key and public key, I cant find the address hex. Does the public keys is receive address.?

**Comment by Akuukis** [comment]
In Stellar address is not written as hex, but base32. Also public key is the receiving address, unless you do magic with signers yourself.

**Comment by nagarajmanjunath** [comment]
Thanks, Is it possible to derive the address from the public key
