### ISSUE TITLE
Aarry length and seceret key length i different

### ISSUE THREAD

**Issue by Nagaraj007** [chatch/stellar-hd-wallet#9]
When i use 
var secret_key=wallet.getSecret(0);
console.log("secret_key",secret_key);

"SCVVKNLBHOWBNJYHD3CNROOA2P3K35I5GNTYUHLLMUHMHWQYNEI7LVED"
its generating **28 byte** of hash value.

but when the get the keypair value 
var keyPair=wallet.getKeypair(0);

i ll get secret_key  **32 bytes**,

why hash and key-pair array is different..?

**Comment by chatch** [comment]
hi @Nagaraj007, the secret_key in keypair is the raw 32 bytes.  the 28 bytes / getSecret one is an encoded form - a version byte and checksum are prepended to the raw bytes, then it's all base32 encoded. the result is 56 chars / 28 bytes ...  checkout the strkey.js module in stellar-base for details.
